spring.application.name=fridgeManager
server.servlet.context-path=/fridgeManager
server.port=125
spring.thymeleaf.cache=false
server.address=127.0.0.1
server.servlet.session.cookie.http-only=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.session.tracking-modes=cookie
# =============================
# H2データベース設定（組み込みDB）
# =============================

# 組み込みDB・H2の設定
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:db-no-namae
# spring.datasource.username=watashi-no-namae
# spring.datasource.password=watashi-no-pasuwa-do

# JPA設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update 
# create だと起動ごとにテーブルが初期化されるので注意

# H2 Web Consoleを有効化（ブラウザ確認用）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# コンソールにSQL出力
spring.jpa.show-sql=true

# 詳細なSQLロギング（Hibernateのログ出す）
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE