spring.application.name=fridgeManager
server.servlet.context-path=/fridgeManager
server.port=0125
spring.thymeleaf.cache=false
server.address=127.0.0.1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/wakaran
spring.datasource.username=namae
spring.datasource.password=pasuwa-do
server.servlet.session.cookie.http-only=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.session.tracking-modes=cookie